version: "3.7"
services:
  app:
    build:
      args:
        user: indra
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: testing
    container_name: testing-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - testing

  db:
    image: mysql:5.7
    container_name: testing-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - testing

  nginx:
    image: nginx:alpine
    container_name: testing-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - testing

networks:
  testing:
    driver: bridge